name: Staging Deploy to Amazon ECS

on:
  push:
    branches: ["develop"]

env:
  AWS_REGION: sa-east-1                   # set this to your preferred AWS region, e.g. us-west-1                                               # file, e.g. .aws/task-definition.json
  

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Build web
      uses: actions/setup-node@v3
      with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
    - run: npm install --force
    - run: npx pretty-quick --staged
    - run: npx eslint src/ --fix

    - name: Deploy web
      run: |
        npm run build --if-present
        aws s3 sync build/ s3://cbcv-staging-web --cache-control 'public, max-age=31536000, must-revalidate' --delete
        aws cloudfront create-invalidation --distribution-id E2SN6EGDG9S3KD --paths '/*'
        
